name: notrunning
on:
  schedule:
    - cron: "*/7 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: get
      run: |
        curl https://xshss.sse.codesandbox.io/lyrics?artist=disturbed&song=stricken
