name: notrunning
on: 
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: get
      run: |
        curl https://xshss.sse.codesandbox.io/lyrics?artist=disturbed&song=stricken
